db:
  image: "mysql:5.7"
  environment:
    MYSQL_USER: root
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: tsampi


server:
  environment:
    DATABASE_USER: root
    DATABASE_PASSWORD: pass
    DATABASE_NAME: tsampi

  build: .
  volumes:
    - .:/code/
    - ./docker_home:/root/
  hostname: tsampi
  command: manage runserver 0.0.0.0:8080
  ports:
    - "8080:8080"
  links:
    - db
  entrypoint:
    - bash
    - /code/entrypoint.sh

