version: '2'
services:
    db:
      image: "mysql:5.7"
      environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: tsampi
      expose:
        - "3306"


    server:
      environment:
       - DATABASE_USER=root
       - DATABASE_PASSWORD=pass
       - DATABASE_NAME=tsampi
       - C_FORCE_ROOT=1
       - TSAMPI_GPG_FINGERPRINT
       - TSAMPI_CHAIN
       - BROKER_URL=amqp://celery:celery@rabbitmq:5672//

      build: .
      volumes:
        - .:/code/
        - ./docker_home:/root/
      hostname: tsampi
      command: devserver
      ports:
        - "8080:8080"
      links:
        - db
        - rabbitmq
      entrypoint:
        - bash
        - /code/entrypoint.sh


    rabbitmq:
        image: "rabbitmq:3.6"
        environment:
         - RABBITMQ_DEFAULT_VHOST=/
         - RABBITMQ_DEFAULT_USER=celery
         - RABBITMQ_DEFAULT_PASS=celery

    worker:
      environment:
        - BROKER_URL=amqp://celery:celery@rabbitmq:5672//

      build: .
      volumes:
        - .:/code/
        - ./docker_home:/root/
      hostname: tsampi-worker
      links:
        - db
        - rabbitmq

      command: [./entrypoint.sh, manage, celery]
