db:
  image: "postgres:9.5"

server:
  build: .
  volumes:
    - .:/code/
    - ./docker_home:/root/
  hostname: tsampi
  command: manage runserver 0.0.0.0:8000
  ports:
    - "8080:8080"
  links:
    - db
  entrypoint:
    - bash
    - /code/entrypoint.sh

